<?php include __DIR__ . '/../template/top.phtml'; ?>

<div class="container signup">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="card">
                <div class="card-header">Sign up!</div>
                <div class="card-body">
                </div>
            </div>
        </div>

    </div>
</div>



















<?php include __DIR__ . '/../template/botton.phtml'; ?>